lms/authors/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_authors, name='all_authors'),
    path('book-signings/', views.book_signings, name='book_signings'),
    path('mvt/', views.mvt, name='mvt'),
]

lms/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
    path('authors/', include('authors.urls')), 
    path('', include('inheritance.urls')), 
]

lms/inheritance/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.demo_inheritance, name="demo_inheritance")
]

lms/library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('books/', views.book_list, name='book_list'),
    
]

lms/authors/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

lms/inheritance/models.py
from django.db import models

# Create your models here.

lms/library/models.py
from django.db import models

# Create your models here.
from authors.models import Author

class Book(models.Model):
    author = models.ForeignKey(Author,on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    number_of_pages = models.PositiveIntegerField()
    published_on = models.DateField()

    def __str__(self):
        return f"{self.title} by {self.author}"

lms/authors/views.py
from django.shortcuts import render
from.models import Author
# Create your views here.
from library.models import Book

def all_authors(request):
    return render(request, "Authors/authors.html")

def book_signings(request):
    return render(request, "Authors/book-signings.html")

def mvt(request):
    author_info = Author.objects.order_by("birth_date")
    authors= Author.objects.all()
    book_info = Book.objects.order_by("-title") #descending order

    context = {
        "author_dob" : author_info, 
        "books" : book_info,
        "authors" : authors,

    }
    return render(request, "Authors/mvt.html", context)

lms/inheritance/views.py
from django.shortcuts import render

# Create your views here.
def demo_inheritance(request):
    return render(request, "inheritance/demo.html")

lms/library/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, "Library/home.html")

def book_list(request):
    return render(request,"Library/list-of-books.html")

lms/templates/Authors/authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authors</title>
</head>
<body>
   <h2>List of Authors</h2> 
</body>
</html>

lms/templates/Authors/book-signings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Signings</title>
</head>
<body>
    <h2>Upcoming book signings</h2>
</body>
</html>

lms/templates/Authors/mvt.html
{% extends "partials/base.html" %}

{% block content %}
<h1>Authors Ordered by DOB</h1>
{% for author in author_dob %}
      <p>First Name : {{  author.first_name }}</p>
      <p>Last Name : {{  author.last_name }}</p>
      <p>Date of birth : {{  author.birth_date }}</p>


{% endfor %}

<h1>Authors in Default Order</h1>
{% for author in authors %}
      <p>First Name : {{  author.first_name }}</p>
      <p>Last Name : {{  author.last_name }}</p>
      <p>Date of birth : {{  author.birth_date }}</p>


{% endfor %}


{% comment %} <h1>test</h1>
{% for book in books %}
<p>{{ book }}</p>
{% endfor %} {% endcomment %}
<h1>Book Info</h1>
{% for book in books %}
<h3>{{ book.title }}</h3>
<p>Written By: {{ book.author }}</p>
<p>Published on: {{ book.published_on }}</p>
<p>It has {{ book.number_of_pages }} pages</p>


{% endfor %}

<h1>Authors And Their Books</h1>
{% for author in authors %}

    {% for book in author.book_set.all %}
    <h3>{{ author }}</h3>
    <p>{{ book }}</p>
    {% endfor %}

{% endfor %}

{% endblock content %}

lms/templates/Library/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Library Landing Page</title>
</head>
<body>
    <h1>Library landing page</h1>
</body>
</html>

lms/templates/Library/list-of-books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List of Books</title>
</head>
<body>
    <h2>List of Books</h2>
</body>
</html>

lms/templates/inheritance/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

lms/templates/partials/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% block title %}LMS{% endblock title %}
</head>
<body>
    {% block content %} {% endblock content %}
</body>
</html>